version: "3"

services:
  app:
    image: renater/simplescalevm:${PROVIDER}-test
    container_name: simplescalevm
    hostname: simplescalevm
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
