version: "3"

services:
  app:
    image: renater/simplescalevm:${PROVIDER}-test
    container_name: simplescalevm
    hostname: simplescalevm
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    volumes:
      - ./cloud-init.sh:/${OPENSTACK_CLOUD_INIT_FILE}
