#!/usr/bin/python3
"""
Configure the Openstack provider.

Variables:
    OPENSTACK_SCALED_NAME
    OPENSTACK_SCALED_CLOUD_INIT_FILE
    OPENSTACK_SCALED_FLAVOR
    OPENSTACK_FLOATING_IP_DESCRIPTION
    OPENSTACK_SCALED_IMAGE
    OPENSTACK_IP_VERSION
    OPENSTACK_KEYPAIR
    OPENSTACK_METADATA_KEY
    OPENSTACK_METADATA_SCALED_VALUE
    OPENSTACK_SCALED_NETWORK

    OPENSTACK_AUTOSCALER_NAME
    OPENSTACK_AUTOSCALER_CLOUD_INIT_FILE
    OPENSTACK_AUTOSCALER_FLAVOR
    OPENSTACK_AUTOSCALER_IMAGE
    OPENSTACK_METADATA_AUTOSCALER_VALUE
    OPENSTACK_AUTOSCALER_NETWORK
"""

import os


# Create Openstack environment parameters
OPENSTACK_SCALED_NAME = os.getenv("OPENSTACK_SCALED_NAME", "server")
OPENSTACK_SCALED_CLOUD_INIT_FILE = os.getenv("OPENSTACK_SCALED_CLOUD_INIT_FILE")
OPENSTACK_SCALED_FLAVOR = os.getenv("OPENSTACK_SCALED_FLAVOR", "d2-8")
OPENSTACK_FLOATING_IP_DESCRIPTION = os.getenv("OPENSTACK_FLOATING_IP_DESCRIPTION", "server")
OPENSTACK_SCALED_IMAGE = os.getenv("OPENSTACK_SCALED_IMAGE", "Debian 11")
OPENSTACK_IP_VERSION = int(os.getenv("OPENSTACK_IP_VERSION", "4"))
OPENSTACK_KEYPAIR = os.getenv("OPENSTACK_KEYPAIR")
OPENSTACK_METADATA_KEY = os.getenv("OPENSTACK_METADATA_KEY", "group")
OPENSTACK_METADATA_SCALED_VALUE = os.getenv("OPENSTACK_METADATA_SCALED_VALUE", "scaled")
OPENSTACK_SCALED_NETWORK = os.getenv("OPENSTACK_SCALED_NETWORK", "Ext-Net")

# Autoscaling specific parameters
OPENSTACK_AUTOSCALER_NAME = os.getenv("OPENSTACK_AUTOSCALER_NAME", "autoscaler")
OPENSTACK_AUTOSCALER_CLOUD_INIT_FILE = os.getenv("OPENSTACK_AUTOSCALER_CLOUD_INIT_FILE")
OPENSTACK_AUTOSCALER_FLAVOR = os.getenv("OPENSTACK_AUTOSCALER_FLAVOR", "d2-8")
OPENSTACK_AUTOSCALER_IMAGE = os.getenv("OPENSTACK_AUTOSCALER_IMAGE", "Debian 11")
OPENSTACK_METADATA_AUTOSCALER_VALUE = os.getenv("OPENSTACK_METADATA_AUTOSCALER_VALUE", "autoscaler")
OPENSTACK_AUTOSCALER_NETWORK = os.getenv("OPENSTACK_AUTOSCALER_NETWORK", "Ext-Net")
OPENSTACK_AUTOSCALER_MIN_REPLICA = int(os.getenv("OPENSTACK_AUTOSCALER_MIN_REPLICA", "3"))
