name: Release Workflow

on: [release]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: ["openstack"]
    steps:
      - name: Set versions to push on DockerHub
        run: |
          echo "VERSION_FULL=$(echo ${{ github.event.release.tag_name }})" >> $GITHUB_ENV
          echo "VERSION_MEDIUM=$(echo ${{ github.event.release.tag_name }} | cut -d '.' -f -2)" >> $GITHUB_ENV
          echo "VERSION_SHORT=$(echo ${{ github.event.release.tag_name }} | cut -d '.' -f -1)" >> $GITHUB_ENV
          echo "VERSION_LATEST=$(echo latest)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: renater
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: PROVIDER=${{ matrix.provider }}
          tags: >-
            renater/simplescalevm:${{ matrix.provider }}-${{ env.VERSION_FULL }},
            renater/simplescalevm:${{ matrix.provider }}-${{ env.VERSION_MEDIUM }},
            renater/simplescalevm:${{ matrix.provider }}-${{ env.VERSION_SHORT }},
            renater/simplescalevm:${{ matrix.provider }}-${{ env.VERSION_LATEST }}
